namespace: dev

global:
  image:
    repository: springcommunity
    tag: latest
  env: dev
  domain: dev.petclinic.com
  dockerRepo: springcommunity
  configServerUrl: http://config-server:8888
  imagePullPolicy: IfNotPresent
  discoveryServerUrl: http://discovery-server:8761/eureka

config-server:
  image: config-server
  tag: latest
  port: 8888

discovery-server:
  image: discovery-server
  tag: latest
  port: 8761

vets-service:
  image: vets-service
  tag: latest
  port: 8083

customers-service:
  image: customers-service
  tag: latest
  port: 8081

api-gateway:
  image: api-gateway
  tag: latest
  port: 8080

services:
  config-server:
    port: 8888
    nodePort: 30001
  discovery-server:
    port: 8761
    nodePort: 30002
  api-gateway:
    port: 8080
    nodePort: 30003
  customers-service:
    port: 8081
    nodePort: 30004

ingress:
  enabled: true
  host: dev.petclinic.com
